### ISSUE TITLE
Port conflict with docker desktop

### ISSUE THREAD

**Issue by zbalkan** [RIPE-NCC/ipv6-security-lab#8]
The IPv6-security-lab uses http://localhost:8080 by default. However, it creates conflicts when Docker Desktop is installed and port 8080 is assigned to it. It did not throw any error message about the conflict though. I had to:

-  run `vagrant halt`
- kill docker executable, 
- stop the docker service, 
- modify hosts file,
- comment out docker/k8s entries,
- run `vagrant up` again.

It might be because of my setup. So needs to be verified if this is an issue with ipv6-aecurity-lab.

**Comment by oskar456** [comment]
Hello, thank you for your report. In my test, Vagrant is pretty verbal when something is listening on the host port 8080:

```
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 8080 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 80, host: 1234
…
```

You can change the port used on the localhost by adding these lines to your Vagrantfile that is generated by the `vagrant init` command. This will change the forwarded port to 8081:

```ruby
config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1", id: "web", disabled: true
config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"
```
I will add this to the README.

**Comment by zbalkan** [comment]
Thank you for you help. It's my lack of experience in Vagrant.
